default:
	(cd util; make)
	(cd generic; make)
	(cd inferelator; make)
	(cd tileViewer; make)
	(cd ip; make)
	(cd prolinks; make)


clean:
	find . -name "*.class" -exec rm {} ';'
	find . -name "*.jar" -exec rm {} ';'
	
